# Generated by Django 5.2.7 on 2025-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
                ('marital', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('default', models.CharField(max_length=3)),
                ('balance', models.IntegerField()),
                ('housing', models.CharField(max_length=3)),
                ('loan', models.CharField(max_length=3)),
                ('contact', models.CharField(max_length=20)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('campaign', models.IntegerField()),
                ('pdays', models.IntegerField()),
                ('previous', models.IntegerField()),
                ('poutcome', models.CharField(max_length=20)),
                ('prediction', models.CharField(blank=True, max_length=3, null=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Predicción de Cliente',
                'verbose_name_plural': 'Predicciones de Clientes',
            },
        ),
    ]
