# Generated by Django 4.2.6 on 2025-10-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_json', models.JSONField()),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('probability', models.JSONField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
