# Generated by Django 4.2.6 on 2025-10-04 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_streamingprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchresult',
            name='batch_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='batch_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='positive_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batchresult',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streamingprediction',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='streamingprediction',
            name='input_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streamingprediction',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
