# Generated by Django 4.2.6 on 2025-10-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_batchresult_batch_key_batchresult_batch_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchresult',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='batch_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='confusion_matrix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='f1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Tiempo de procesamiento en segundos', null=True),
        ),
        migrations.AlterField(
            model_name='batchresult',
            name='recall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamingprediction',
            name='prediction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
