# Generated by Django 4.2.6 on 2025-10-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0004_alter_batchresult_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchresult',
            name='records_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='streamingprediction',
            name='input_json',
            field=models.JSONField(default=dict),
        ),
    ]
